language: cpp
sudo: false


# don't create redundant code coverage reports
# - AUTOTOOLS=yes COVERAGE=yes BUILD=static
# - AUTOTOOLS=no COVERAGE=yes BUILD=shared
# - AUTOTOOLS=no COVERAGE=no BUILD=static

# further speed up day by day travis-ci builds
# re-enable this if you change the makefiles
# this will still catch all coding errors!
# - AUTOTOOLS=yes COVERAGE=no BUILD=static

# currenty there are various issues when
# built with coverage, clang and autotools
# - AUTOTOOLS=yes COVERAGE=yes BUILD=shared

matrix:
  include :
    - os: osx
      compiler: clang
      env: AUTOTOOLS=yes COVERAGE=no BUILD=shared

script:
  - ./script/ci-build-libsass
  - ./script/ci-build-plugin math
  - ./script/ci-build-plugin glob
  - ./script/ci-build-plugin digest
  - ./script/ci-build-plugin tests
before_install: ./script/ci-install-deps
install: ./script/ci-install-compiler
after_success: ./script/ci-report-coverage
